import { SymmetryConfig } from './symmetryConfig.js';

export const DEFAULT_SYMBOL_COLOR = '#d43d79';
export const DEFAULT_CLEAR_COLOR = '#b6bb06';
export const DEFAULT_SUB_COLOR = '#aeb0cd';

// New worlds start with these groups. The developer screen exports independent
// configurations for every world when its code replaces STAGE_WORLDS.
const DEFAULT_WORLD_STAGES = [
	{
		group: 'p1',
		symbols: [],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: false,
		allowFlip: false,
	},
	{
		group: 'pm',
		symbols: [2],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: false,
		allowFlip: true,
	},
	{
		group: 'p2',
		symbols: [9],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: false,
	},
	{
		group: 'p2mm',
		symbols: [11, 14],
		clearSymbols: [5],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p4',
		symbols: [5],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: false,
	},
	{
		group: 'p4mm',
		symbols: [11, 16],
		clearSymbols: [5],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p3',
		symbols: [5],
		clearSymbols: [],
		initialAngles: [0, 60, 120, 180, 240, 300],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: false,
	},
	{
		group: 'p3m1',
		symbols: [7, 10],
		clearSymbols: [5],
		initialAngles: [0, 60, 120, 180, 240, 300],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p2mg',
		symbols: [2, 5, 10],
		clearSymbols: [13],
		initialAngles: [0, 180],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p4mg',
		symbols: [5, 10, 11, 12, 13],
		clearSymbols: [14],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p31m',
		symbols: [5, 7, 8, 11],
		clearSymbols: [12],
		initialAngles: [0, 60, 120, 180, 240, 300],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'pg',
		symbols: [2],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: false,
		allowFlip: true,
	},
	{
		group: 'cm',
		symbols: [2, 4, 5],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: false,
		allowFlip: true,
	},
	{
		group: 'pgg',
		symbols: [1, 4, 9],
		clearSymbols: [6],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'c2mm',
		symbols: [10, 20, 21],
		clearSymbols: [],
		initialAngles: [0, 90, 180, 270],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p6',
		symbols: [5, 7, 8, 9],
		clearSymbols: [1],
		initialAngles: [0, 60, 120, 180, 240, 300],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
	{
		group: 'p6mm',
		symbols: [1, 17],
		clearSymbols: [2, 3],
		initialAngles: [0, 60, 120, 180, 240, 300],
		sizeMin: 0.4,
		sizeMax: 0.5,
		allowRotate: true,
		allowFlip: true,
	},
];

// Paste the developer screen's exported STAGE_WORLDS here to publish edits.
const copyStage = (stage) => ({
	...stage,
	symbols: [...stage.symbols],
	clearSymbols: [...stage.clearSymbols],
	initialAngles: [...stage.initialAngles],
});
export const STAGE_WORLDS = [
	{
		id: 1,
		theme: {
			background: '#3c3e59',
			foreground: '#f0f2f5',
			symbolColor: '#d43d79',
			clearColor: '#b6bb06',
			subColor: '#aeb0cd',
		},
		stages: [
			{
				group: 'p1',
				symbols: [],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pm',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2',
				symbols: [9],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2mm',
				symbols: [11, 14],
				clearSymbols: [5],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4',
				symbols: [5],
				clearSymbols: [1],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4mm',
				symbols: [11, 14, 16, 17],
				clearSymbols: [5],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p3',
				symbols: [5],
				clearSymbols: [6],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p3m1',
				symbols: [7, 8, 10],
				clearSymbols: [5],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2mg',
				symbols: [2, 5, 10],
				clearSymbols: [13],
				initialAngles: [0, 180],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4mg',
				symbols: [5, 10, 11, 12, 13],
				clearSymbols: [14],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p31m',
				symbols: [5, 7, 8, 11],
				clearSymbols: [12],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pg',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'cm',
				symbols: [2, 4, 5],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pgg',
				symbols: [1, 4, 9],
				clearSymbols: [6],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'c2mm',
				symbols: [10, 15, 18],
				clearSymbols: [20, 21],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p6',
				symbols: [5, 6, 7, 8, 9],
				clearSymbols: [1],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p6mm',
				symbols: [1, 17],
				clearSymbols: [22, 23],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
		],
	},
	{
		id: 2,
		theme: {
			background: '#762323',
			foreground: '#f0f2f5',
			symbolColor: '#4675be',
			clearColor: '#b6bb06',
			subColor: '#dd9797',
		},
		stages: [
			{
				group: 'p1',
				symbols: [],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2',
				symbols: [5],
				clearSymbols: [1, 9],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4',
				symbols: [1],
				clearSymbols: [5, 6, 7],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p3',
				symbols: [3],
				clearSymbols: [1, 2],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p6',
				symbols: [5, 10],
				clearSymbols: [3],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pm',
				symbols: [1, 3],
				clearSymbols: [2],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pg',
				symbols: [1, 3],
				clearSymbols: [2],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'cm',
				symbols: [1, 5],
				clearSymbols: [2],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2mm',
				symbols: [2, 11],
				clearSymbols: [5, 14],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p2mg',
				symbols: [4, 13],
				clearSymbols: [10, 11],
				initialAngles: [0, 180],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'pgg',
				symbols: [6, 8],
				clearSymbols: [1, 2],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'c2mm',
				symbols: [13, 20, 21],
				clearSymbols: [15, 18],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4mm',
				symbols: [11, 18, 19],
				clearSymbols: [5, 10, 12, 13, 15],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p4mg',
				symbols: [14, 16, 18],
				clearSymbols: [5, 10, 11, 12, 13],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p3m1',
				symbols: [5, 9],
				clearSymbols: [10],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p31m',
				symbols: [12, 13],
				clearSymbols: [5, 6],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
			{
				group: 'p6mm',
				symbols: [9, 22, 23],
				clearSymbols: [3, 16, 24, 25],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: false,
			},
		],
	},
	{
		id: 3,
		theme: {
			background: '#484619',
			foreground: '#f0f2f5',
			symbolColor: '#be4646',
			clearColor: '#bbbb06',
			subColor: '#b1b79e',
		},
		stages: [
			{
				group: 'p1',
				symbols: [],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: false,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'pm',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p2',
				symbols: [9],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p3',
				symbols: [5],
				clearSymbols: [1, 2, 3],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'pg',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p4',
				symbols: [5],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: false,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'cm',
				symbols: [2, 5],
				clearSymbols: [3],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: false,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p2mm',
				symbols: [11, 14],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'pgg',
				symbols: [6, 9],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p4mm',
				symbols: [5, 11],
				clearSymbols: [18, 19, 20, 21],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.25,
				sizeMax: 0.35,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p2mg',
				symbols: [10, 11, 13],
				clearSymbols: [],
				initialAngles: [0, 180],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p4mg',
				symbols: [1, 5, 10],
				clearSymbols: [14, 16, 18],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.25,
				sizeMax: 0.35,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'c2mm',
				symbols: [10, 14, 17],
				clearSymbols: [13, 22, 23],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.2,
				sizeMax: 0.3,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p31m',
				symbols: [5, 6, 12],
				clearSymbols: [14, 15],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p6',
				symbols: [5, 7],
				clearSymbols: [1],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: false,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p3m1',
				symbols: [5, 7],
				clearSymbols: [1],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.3,
				sizeMax: 0.4,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
			{
				group: 'p6mm',
				symbols: [12, 13, 17],
				clearSymbols: [1, 28, 29, 31, 32],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.2,
				sizeMax: 0.3,
				allowRotate: true,
				allowFlip: true,
				doubleMode: true,
				blindMode: false,
			},
		],
	},
	{
		id: 4,
		theme: {
			background: '#3a2546',
			foreground: '#f0f2f5',
			symbolColor: '#be4646',
			clearColor: '#bbbb06',
			subColor: '#bdadcd',
		},
		stages: [
			{
				group: 'p1',
				symbols: [],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.7,
				sizeMax: 0.8,
				allowRotate: false,
				allowFlip: false,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'pm',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p2',
				symbols: [9],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'pg',
				symbols: [2],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p4',
				symbols: [5],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p3',
				symbols: [5],
				clearSymbols: [],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p2mm',
				symbols: [5, 14],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'cm',
				symbols: [2, 4],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: false,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p2mg',
				symbols: [1, 10, 11, 13],
				clearSymbols: [5],
				initialAngles: [0, 180],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'c2mm',
				symbols: [15, 18, 20, 21],
				clearSymbols: [],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p4mm',
				symbols: [11, 18, 21],
				clearSymbols: [5],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p6',
				symbols: [5, 9],
				clearSymbols: [2],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: false,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p3m1',
				symbols: [10, 11],
				clearSymbols: [2],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'pgg',
				symbols: [6, 9],
				clearSymbols: [1],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.6,
				sizeMax: 0.7,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p4mg',
				symbols: [16, 18, 19],
				clearSymbols: [5],
				initialAngles: [0, 90, 180, 270],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p31m',
				symbols: [12, 13, 14, 15],
				clearSymbols: [1],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.5,
				sizeMax: 0.6,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
			{
				group: 'p6mm',
				symbols: [24, 32],
				clearSymbols: [1, 17],
				initialAngles: [0, 60, 120, 180, 240, 300],
				sizeMin: 0.4,
				sizeMax: 0.5,
				allowRotate: true,
				allowFlip: true,
				doubleMode: false,
				blindMode: true,
			},
		],
	},
];

export const buildStages = (worlds) =>
	worlds.flatMap((world, worldIndex) =>
		world.stages.map((config, index) => ({
			...config,
			doubleMode: config.doubleMode ?? world.id === 3,
			blindMode: config.blindMode ?? world.id === 4,
			symbolColor: world.theme.symbolColor || DEFAULT_SYMBOL_COLOR,
			clearColor: world.theme.clearColor || DEFAULT_CLEAR_COLOR,
			theme: world.theme,
			world: world.id,
			worldIndex,
			level: index + 1,
			number:
				worlds.slice(0, worldIndex).reduce((sum, earlier) => sum + earlier.stages.length, 0) +
				index +
				1,
			key: `${world.id}-${index + 1}`,
			hex: SymmetryConfig[config.group]?.system === 'hexagonal',
		})),
	);

export const STAGES = buildStages(STAGE_WORLDS);
